# Generated by Django 5.0.3 on 2024-04-01 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('nom', models.CharField(blank=True, max_length=20, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canton',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foretmaamora',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('nom', models.CharField(blank=True, max_length=21, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foretmaamora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupemamora',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('layer_id', models.FloatField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=14, null=True)),
                ('nom_groupe', models.CharField(blank=True, max_length=20, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groupemamora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcellaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('parcelle', models.CharField(blank=True, max_length=4, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parcellaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid_1', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
    ]
