# Generated by Django 5.0.3 on 2024-04-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='communes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foretmaamora',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groupemamora',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='parcellaire',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': True},
        ),
    ]
