# Generated by Django 5.0.3 on 2024-04-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0002_alter_canton_options_alter_communes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='foret',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.foretmaamora'),
            preserve_default=False,
        ),
    ]
