# Generated by Django 5.0.3 on 2024-04-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0003_canton_foret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canton',
            name='foret',
        ),
        migrations.AlterField(
            model_name='canton',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foretmaamora',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
