# Generated by Django 5.0.3 on 2024-04-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0005_canton_foret_alter_communes_id_alter_groupemamora_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foretmaamora',
            new_name='Foret',
        ),
    ]
