# Generated by Django 5.0.3 on 2024-04-01 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0006_rename_foretmaamora_foret'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcellaire',
            name='canton',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.canton'),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='groupe',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.groupemamora'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=20, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('revolution', models.FloatField(blank=True, null=True)),
                ('foret', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.foret')),
            ],
        ),
        migrations.AddField(
            model_name='groupemamora',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.serie'),
        ),
    ]
