# Generated by Django 5.0.3 on 2024-04-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0007_parcellaire_canton_parcellaire_groupe_serie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foret',
            table='foret',
        ),
    ]
