# Generated by Django 5.0.3 on 2024-04-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0008_alter_foret_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foret',
            table='foretmaamora',
        ),
    ]
