# Generated by Django 5.0.3 on 2024-04-01 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0009_alter_foret_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.provinces'),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.communes'),
        ),
        migrations.AddField(
            model_name='provinces',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.regions'),
        ),
        migrations.AlterField(
            model_name='canton',
            name='foret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.foret'),
        ),
        migrations.AlterField(
            model_name='parcellaire',
            name='canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.canton'),
        ),
        migrations.AlterField(
            model_name='parcellaire',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.groupemamora'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='foret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.foret'),
        ),
    ]
