# Generated by Django 5.0.3 on 2024-04-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0010_communes_province_parcellaire_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DRANEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='DFP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.dfp'),
        ),
        migrations.CreateModel(
            name='DPANEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('DRANEF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.dranef')),
            ],
        ),
        migrations.CreateModel(
            name='ZDTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('DPANEF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.dpanef')),
            ],
        ),
        migrations.AddField(
            model_name='dfp',
            name='ZDTF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.zdtf'),
        ),
    ]
