# Generated by Django 5.0.3 on 2024-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0011_dfp_dranef_parcellaire_dfp_dpanef_zdtf_dfp_zdtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcellaire',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='limite_Est',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='limite_Nord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='limite_Sud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcellaire',
            name='limite_ouest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcellaire',
            name='parcelle',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
