# Generated by Django 5.0.3 on 2024-04-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0012_parcellaire_description_parcellaire_limite_est_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcellaire',
            name='parcelle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
