# Generated by Django 5.0.3 on 2024-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0013_alter_parcellaire_parcelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communes',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dfp',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dpanef',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='dranef',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='provinces',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='zdtf',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='dfp',
            name='siege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpanef',
            name='siege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dranef',
            name='siege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zdtf',
            name='siege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
