# Generated by Django 5.0.3 on 2024-04-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0014_rename_name_communes_nom_rename_name_dfp_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.parcellaire')),
            ],
        ),
        migrations.CreateModel(
            name='Essenceliège',
            fields=[
                ('essences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cubage.essences')),
                ('Typeliège', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('Cubage.essences',),
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=100, null=True)),
                ('Essence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.essences')),
            ],
        ),
    ]
