# Generated by Django 5.0.3 on 2024-04-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0015_essences_essenceliège_regime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essences',
            old_name='nom',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='essences',
            old_name='parcelle',
            new_name='Parcelle',
        ),
    ]
