# Generated by Django 5.0.3 on 2024-04-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0016_rename_nom_essences_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifCubage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(blank=True, max_length=100, null=True)),
                ('typeVolume', models.CharField(blank=True, max_length=100, null=True)),
                ('UniteMesure', models.CharField(blank=True, max_length=100, null=True)),
                ('circonference_min', models.IntegerField(blank=True, null=True)),
                ('circonference_max', models.IntegerField(blank=True, null=True)),
                ('Regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.regime')),
            ],
        ),
    ]
