# Generated by Django 5.0.3 on 2024-04-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0017_tarifcubage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regime',
            name='Essence',
        ),
        migrations.AddField(
            model_name='tarifcubage',
            name='Essence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.essences'),
        ),
    ]
