# Generated by Django 5.0.3 on 2024-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0018_remove_regime_essence_tarifcubage_essence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essences',
            name='Parcelle',
        ),
        migrations.AddField(
            model_name='essences',
            name='Parcelle',
            field=models.ManyToManyField(to='Cubage.parcellaire'),
        ),
    ]
