# Generated by Django 5.0.3 on 2024-04-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0020_remove_essences_parcelle_essences_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='essences',
            name='canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.canton'),
        ),
        migrations.RemoveField(
            model_name='essences',
            name='Parcelle',
        ),
        migrations.AddField(
            model_name='essences',
            name='Parcelle',
            field=models.ManyToManyField(null=True, to='Cubage.parcellaire'),
        ),
    ]
