# Generated by Django 5.0.3 on 2024-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0021_essences_canton_remove_essences_parcelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essences',
            name='Parcelle',
            field=models.ManyToManyField(to='Cubage.parcellaire'),
        ),
    ]
