# Generated by Django 5.0.3 on 2024-04-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0022_alter_essences_parcelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifcubage',
            name='Regime',
        ),
        migrations.AddField(
            model_name='essences',
            name='Regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.regime'),
        ),
    ]
