# Generated by Django 5.0.3 on 2024-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0023_remove_tarifcubage_regime_essences_regime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essences',
            name='canton',
        ),
        migrations.AddField(
            model_name='essences',
            name='canton',
            field=models.ManyToManyField(to='Cubage.canton'),
        ),
    ]
