# Generated by Django 5.0.3 on 2024-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0024_remove_essences_canton_essences_canton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essences',
            name='canton',
        ),
    ]
