# Generated by Django 5.0.3 on 2024-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0025_remove_essences_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='essences',
            name='canton',
            field=models.ManyToManyField(to='Cubage.canton'),
        ),
    ]
