# Generated by Django 5.0.3 on 2024-04-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0026_essences_canton'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEchantillonage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation_de_calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surface_de_placette', models.IntegerField(blank=True, null=True)),
                ('Nombre_de_placette', models.IntegerField(blank=True, null=True)),
                ('TarifCubage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.tarifcubage')),
                ('TypeEchantillonage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.typeechantillonage')),
            ],
        ),
    ]
