# Generated by Django 5.0.3 on 2024-04-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0027_typeechantillonage_operation_de_calcul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_de_calcul',
            old_name='Nombre_de_placette',
            new_name='Nombre_de_strate',
        ),
    ]
