# Generated by Django 5.0.3 on 2024-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0028_rename_nombre_de_placette_operation_de_calcul_nombre_de_strate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('volume_hectares', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='liste_de_bois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circonferance_1m30', models.IntegerField(blank=True, null=True)),
                ('volume_individuel', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('nombre_de_bois_classe', models.IntegerField(blank=True, null=True)),
                ('volume_total_classe', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('Placette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.placette')),
            ],
        ),
        migrations.CreateModel(
            name='Strate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superficie_de_la_strate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('nombre_placette', models.IntegerField(blank=True, null=True)),
                ('volume_moyenne_strate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('volume_total_strate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('ecart_type_strate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('erreur_standard', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('intervalle_confience', models.CharField(blank=True, max_length=100, null=True)),
                ('Operation_de_calcul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.operation_de_calcul')),
            ],
        ),
        migrations.AddField(
            model_name='placette',
            name='Strate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.strate'),
        ),
    ]
