# Generated by Django 5.0.3 on 2024-04-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0029_placette_liste_de_bois_strate_placette_strate'),
    ]

    operations = [
        migrations.AddField(
            model_name='strate',
            name='Numero_strate',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
