# Generated by Django 5.0.3 on 2024-04-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0030_strate_numero_strate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strate',
            name='Numero_strate',
        ),
    ]
