# Generated by Django 5.0.3 on 2024-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0032_alter_placette_volume_hectares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul',
            name='superficie_peuplement',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
