# Generated by Django 5.0.3 on 2024-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0033_operation_de_calcul_superficie_peuplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul',
            name='erreur_type_relative',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
