# Generated by Django 5.0.3 on 2024-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0034_operation_de_calcul_erreur_type_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul',
            name='varience_moyenne',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul',
            name='volume_moyenne_peuplement_hectare',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul',
            name='volume_total_du_peuplent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
