# Generated by Django 5.0.3 on 2024-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0035_operation_de_calcul_varience_moyenne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_de_calcul',
            name='erreur_type_relative',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
