# Generated by Django 5.0.3 on 2024-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0036_alter_operation_de_calcul_erreur_type_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strate',
            name='erreur_standard',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
