# Generated by Django 5.0.3 on 2024-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0037_alter_strate_erreur_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste_de_bois',
            name='volume_individuel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='liste_de_bois',
            name='volume_total_classe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operation_de_calcul',
            name='erreur_type_relative',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='strate',
            name='ecart_type_strate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
