# Generated by Django 5.0.3 on 2024-04-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0040_alter_liste_de_bois_volume_individuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strate',
            name='erreur_standard',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
