# Generated by Django 5.0.3 on 2024-04-21 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0041_alter_strate_erreur_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_de_calcul_de_Rendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_peuplement', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('volume_total_de_liege', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('TarifCubage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.tarifcubage')),
            ],
        ),
        migrations.CreateModel(
            name='liste_liege_par_Circonference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circonferance_1m30', models.IntegerField(blank=True, null=True)),
                ('volume_individuel', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('nombre_de_liege_classe', models.IntegerField(blank=True, null=True)),
                ('volume_total_classe', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('operation_de_calcul_de_Rendement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.operation_de_calcul_de_rendement')),
            ],
        ),
    ]
