# Generated by Django 5.0.3 on 2024-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0042_operation_de_calcul_de_rendement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul',
            name='ecart_type_moyenn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
