# Generated by Django 5.0.3 on 2024-04-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0043_operation_de_calcul_ecart_type_moyenn'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste_de_bois',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
