# Generated by Django 5.0.3 on 2024-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0044_liste_de_bois_hauteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste_de_bois',
            name='hauteur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
