# Generated by Django 5.0.3 on 2024-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0045_alter_liste_de_bois_hauteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul',
            name='Nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='Nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
