# Generated by Django 5.0.3 on 2024-04-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0046_operation_de_calcul_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_de_calcul_de_rendement',
            name='TarifCubage',
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='tarif_rendement_liege_male',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_de_calcul_de_rendement_male', to='Cubage.tarifcubage'),
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='tarif_rendement_liege_reproduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_de_calcul_de_rendement_reproduction', to='Cubage.tarifcubage'),
        ),
    ]
