# Generated by Django 5.0.3 on 2024-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0047_remove_operation_de_calcul_de_rendement_tarifcubage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liste_liege_par_circonference',
            old_name='nombre_de_liege_classe',
            new_name='nombre_de_liege_de_male_classe',
        ),
        migrations.RenameField(
            model_name='liste_liege_par_circonference',
            old_name='volume_individuel',
            new_name='volume_individuel_hausse',
        ),
        migrations.RenameField(
            model_name='liste_liege_par_circonference',
            old_name='volume_total_classe',
            new_name='volume_individuel_liege_de_reproduction',
        ),
        migrations.AddField(
            model_name='liste_liege_par_circonference',
            name='nombre_de_liege_de_reproduction_classe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liste_liege_par_circonference',
            name='volume_individuel_liege_male',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='liste_liege_par_circonference',
            name='volume_total_liege_de_male_classe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='liste_liege_par_circonference',
            name='volume_total_liege_de_reproduction_classe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
