# Generated by Django 5.0.3 on 2024-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0048_rename_nombre_de_liege_classe_liste_liege_par_circonference_nombre_de_liege_de_male_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='volume_total_liege_de_male',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='volume_total_liege_de_reproduction',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
