# Generated by Django 5.0.3 on 2024-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0049_operation_de_calcul_de_rendement_volume_total_liege_de_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placette',
            name='Profondeur_de_sol',
            field=models.CharField(blank=True, choices=[('Squelettique', 'Squelettique'), ('Peu profond', 'Peu profond'), ('Profond', 'Profond')], max_length=100, null=True),
        ),
    ]
