# Generated by Django 5.0.3 on 2024-05-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0050_placette_profondeur_de_sol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essences',
            name='canton',
        ),
        migrations.AddField(
            model_name='essences',
            name='canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cubage.canton'),
        ),
    ]
