# Generated by Django 5.0.3 on 2024-05-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0051_remove_essences_canton_essences_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='strate',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
