# Generated by Django 5.0.3 on 2024-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0052_strate_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='placette',
            name='numero_placette',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
