# Generated by Django 5.0.3 on 2024-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0053_placette_numero_placette'),
    ]

    operations = [
        migrations.AddField(
            model_name='placette',
            name='nombre_de_bois_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
