# Generated by Django 5.0.3 on 2024-05-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0054_placette_nombre_de_bois_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='strate',
            name='parcelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.parcellaire'),
        ),
    ]
