# Generated by Django 5.0.3 on 2024-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0055_strate_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strate',
            name='parcelle',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
