# Generated by Django 5.0.3 on 2024-05-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0056_alter_strate_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strate',
            name='parcelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cubage.parcellaire'),
        ),
    ]
