# Generated by Django 5.0.3 on 2024-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0057_alter_strate_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='strate',
            name='groupe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='strate',
            name='parcelle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
