# Generated by Django 5.0.3 on 2024-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0058_strate_groupe_alter_strate_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strate',
            name='parcelle',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
