# Generated by Django 5.0.3 on 2024-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0060_alter_strate_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='Anne_de_demasclage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='groupe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operation_de_calcul_de_rendement',
            name='parcelle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
