# Generated by Django 5.0.3 on 2024-05-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0061_operation_de_calcul_de_rendement_anne_de_demasclage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_de_calcul_de_rendement',
            old_name='Anne_de_demasclage',
            new_name='Annee_de_demasclage',
        ),
    ]
