# Generated by Django 5.0.3 on 2024-05-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cubage', '0062_rename_anne_de_demasclage_operation_de_calcul_de_rendement_annee_de_demasclage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'managed': True, 'verbose_name': 'Canton', 'verbose_name_plural': 'Cantons'},
        ),
        migrations.AlterModelOptions(
            name='communes',
            options={'managed': True, 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='dfp',
            options={'verbose_name': 'DFP', 'verbose_name_plural': 'DFP'},
        ),
        migrations.AlterModelOptions(
            name='dpanef',
            options={'verbose_name': 'DPANEF', 'verbose_name_plural': 'DPANEF'},
        ),
        migrations.AlterModelOptions(
            name='dranef',
            options={'verbose_name': 'DRANEF', 'verbose_name_plural': 'DRANEF'},
        ),
        migrations.AlterModelOptions(
            name='essenceliège',
            options={'verbose_name': 'Essenceliège', 'verbose_name_plural': 'Essencelièges'},
        ),
        migrations.AlterModelOptions(
            name='essences',
            options={'verbose_name': 'Essence', 'verbose_name_plural': 'Essences'},
        ),
        migrations.AlterModelOptions(
            name='foret',
            options={'managed': True, 'verbose_name': 'Forêt', 'verbose_name_plural': 'Forêts'},
        ),
        migrations.AlterModelOptions(
            name='groupemamora',
            options={'managed': True, 'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='operation_de_calcul',
            options={'verbose_name': 'Operation de calcul de volume bois ', 'verbose_name_plural': 'Operations de calcul de volume bois'},
        ),
        migrations.AlterModelOptions(
            name='operation_de_calcul_de_rendement',
            options={'verbose_name': 'Operation de calcul de Rendement liège', 'verbose_name_plural': ' Operations de calcul de Rendement liège '},
        ),
        migrations.AlterModelOptions(
            name='parcellaire',
            options={'managed': True, 'verbose_name': 'Parcellaire', 'verbose_name_plural': 'Parcellaires'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'managed': True, 'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterModelOptions(
            name='regime',
            options={'verbose_name': 'Regime', 'verbose_name_plural': 'Regimes'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': True, 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='tarifcubage',
            options={'verbose_name': 'Tarif de cubage', 'verbose_name_plural': 'Tarifs de cubage'},
        ),
        migrations.AlterModelOptions(
            name='typeechantillonage',
            options={'verbose_name': "Type d'échantillonage", 'verbose_name_plural': "Types d'échantillonage"},
        ),
        migrations.AlterModelOptions(
            name='zdtf',
            options={'verbose_name': 'ZDTF', 'verbose_name_plural': 'ZDTF'},
        ),
    ]
